package com.finobank.ptaplus.SettlementUtils;

public enum SettlementStages {

    INITIALIZATION,
    INITIALIZATION_FAILED,
    P2M_POSTING_RUNNING,
    P2M_POSTING_SUCCEEDED,
    P2M_POSTING_FAILED,

    CBS_SETTLEMENT_STARTED,
    CBS_SETTLEMENT_FAILED,
    CBS_TRANSACTIONS_RUNNING,
    
    IFT_FILE_GENERATION_RUNNING,
    IFT_FILE_GENERATION_SUCCEEDED,
    IFT_FILE_GENERATION_FAILED,

    SETTLEMENT_IFT_RESULT_PENDING,

    SETTLEMENT_IFT_RESULT_RECEIVED,
    IFT_FILE_PROCESSING_RUNNING,
    IFT_FILE_PROCESSING_SUCCEEDED,
    IFT_FILE_PROCESSING_FAILED,
    
    SETTLEMENT
}
