apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: UpdateGLstatus
  namespace: finoptaplus
  labels:
    app: UpdateGLstatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: UpdateGLstatus
  template:
    metadata:
      labels:
        app: UpdateGLstatus
    spec:
      containers:
      - name: UpdateGLstatus
        image: nexus-registry-nexus.apps.ocp4.example.com/UpdateGLstatus:16-10-2023
        env:
          - name: TRMYHOST
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        envFrom:
        - configMapRef:
                name: UpdateGLstatus
        ports:
        - containerPort: 8080
        resources: 
          requests: 
            memory: "64Mi" 
            cpu: "250m" 
          limits: 
            memory: "128Mi" 
            cpu: "500m"
      imagePullSecrets:
      - name: xyz
